"""editted date type to event_time column

Revision ID: 592b650633ee
Revises: b26849e0c8d6
Create Date: 2023-07-27 22:51:44.301176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592b650633ee'
down_revision = 'b26849e0c8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('event_time')

    # ### end Alembic commands ###
